"""Adding Summary and notes field

Revision ID: 0305c3157aac
Revises: 38698b33e615
Create Date: 2016-11-25 02:21:29.455574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0305c3157aac'
down_revision = '38698b33e615'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Formulas', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('Formulas', sa.Column('summary', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Formulas', 'summary')
    op.drop_column('Formulas', 'notes')
    ### end Alembic commands ###
