"""empty message

Revision ID: 180c9f7b79e1
Revises: 
Create Date: 2017-01-15 21:50:18.510421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180c9f7b79e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_name', sa.String(length=64), nullable=True),
    sa.Column('formula_number', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('last_modified', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('base_name', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['Formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Colorants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('colorant_name', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['Formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Colorants')
    op.drop_table('Bases')
    op.drop_table('Formulas')
    # ### end Alembic commands ###
