"""empty message

Revision ID: 2fdc27659b19
Revises: 579a2585f53e
Create Date: 2017-01-23 01:16:31.805399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdc27659b19'
down_revision = '579a2585f53e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Formulas', schema=None) as batch_op:
        batch_op.drop_column('bases')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Formulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bases', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
