"""empty message

Revision ID: 38698b33e615
Revises: 
Create Date: 2016-11-21 02:20:29.958905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38698b33e615'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.String(length=64), nullable=True),
    sa.Column('color_number', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=64), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('last_modified', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Bases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('base_name', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['Formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Colorants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_id', sa.Integer(), nullable=False),
    sa.Column('colorant_name', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formula_id'], ['Formulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Colorants')
    op.drop_table('Bases')
    op.drop_table('Formulas')
    ### end Alembic commands ###
