"""empty message

Revision ID: 579a2585f53e
Revises: 
Create Date: 2017-01-19 00:59:34.394124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '579a2585f53e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('formula_name', sa.String(length=64), nullable=True),
    sa.Column('formula_number', sa.String(length=64), nullable=True),
    sa.Column('customer_name', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('colorants', sa.Text(), nullable=True),
    sa.Column('bases', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('last_modified', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Formulas')
    # ### end Alembic commands ###
