"""empty message

Revision ID: e41e9b43e3da
Revises: 2fdc27659b19
Create Date: 2017-02-02 21:00:01.674209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41e9b43e3da'
down_revision = '2fdc27659b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Formulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_address', sa.String(length=64), nullable=True))
        batch_op.drop_column('summary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Formulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('job_address')

    # ### end Alembic commands ###
